name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
    inputs:
      debug-only:
        description: Run in debug mode
        required: false
        default: 'false'
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          debug-only: ${{ github.event.inputs.debug-only == 'true' }}
          days-before-stale: 365
          days-before-close: 14
          stale-issue-label: stale
          close-issue-label: closed-stale
          exempt-issue-labels: announcement,planning
          exempt-all-milestones: true
          exempt-all-assignees: true
          stale-issue-message: >
            This issue has been automatically marked as stale because it has no recent activity. 
            It will be closed if no further activity occurs. Please comment if you believe this 
            should remain open, otherwise it will be closed in 14 days.
            Thank you for your contributions to this project.
          close-issue-message: >
            Closing due to inactivity.

            If you are looking at this issue in the future and think it should be reopened, 
            please make a commented here and mention natemcmaster so he sees the notification.
          stale-pr-message: >
            This pull request appears to be stale. Please comment if you believe this should remain 
            open and reviewed. If there are no updates, it will be closed in 14 days.
          close-pr-message: >
             Thank you for your contributions to this project. This pull request has been closed due to inactivity.
